package goparser

import (
	"context"
	"testing"
)

func TestProcessor_Process(t *testing.T) {
	src := `
package pkg

type Foo struct {
	Name string
}

func (f *Foo) Bar() int { return 0 }

type Reader interface {
	Read(p []byte) (n int, err error)
}

func NewFoo() *Foo { return nil }
`
	proc := Processor{}
	ctx := context.Background()
	result, err := proc.Process(ctx, "pkg/foo.go", []byte(src))
	if err != nil {
		t.Fatalf("Process: %v", err)
	}
	if result.Package != "pkg" {
		t.Errorf("Package = %q, want pkg", result.Package)
	}
	if len(result.Structs) != 1 {
		t.Fatalf("len(Structs) = %d, want 1", len(result.Structs))
	}
	if result.Structs[0].Name != "Foo" {
		t.Errorf("Struct name = %q, want Foo", result.Structs[0].Name)
	}
	if len(result.Structs[0].Methods) != 1 {
		t.Errorf("len(Methods) = %d, want 1", len(result.Structs[0].Methods))
	}
	if result.Structs[0].Methods[0].Name != "Bar" {
		t.Errorf("Method name = %q, want Bar", result.Structs[0].Methods[0].Name)
	}
	if len(result.Interfaces) != 1 {
		t.Fatalf("len(Interfaces) = %d, want 1", len(result.Interfaces))
	}
	if result.Interfaces[0].Name != "Reader" {
		t.Errorf("Interface name = %q, want Reader", result.Interfaces[0].Name)
	}
	if len(result.Functions) != 1 {
		t.Fatalf("len(Functions) = %d, want 1", len(result.Functions))
	}
	if result.Functions[0].Name != "NewFoo" {
		t.Errorf("Function name = %q, want NewFoo", result.Functions[0].Name)
	}
}

func TestFormatFuncType_GroupedParamsAndNamedResults(t *testing.T) {
	src := `
package pkg

func Merge(dst, src *int) (n int, err error) { return 0, nil }
`
	proc := Processor{}
	result, err := proc.Process(context.Background(), "x.go", []byte(src))
	if err != nil {
		t.Fatalf("Process: %v", err)
	}
	if len(result.Functions) != 1 {
		t.Fatalf("len(Functions) = %d, want 1", len(result.Functions))
	}
	got := result.Functions[0].Signature
	want := "func(dst, src *int) (n int, err error)"
	if got != want {
		t.Errorf("signature = %q, want %q", got, want)
	}
}

func TestProcess_SkipsStdlibKeepsLocalCalls(t *testing.T) {
	src := `
package pkg

import (
	"fmt"
	"path/filepath"
)

func Run() {
	fmt.Println("hi")
	_ = filepath.Base("/a/b") // path/filepath was previously misclassified as local
	helper()
}

func helper() {}
`
	proc := Processor{}
	result, err := proc.Process(context.Background(), "x.go", []byte(src))
	if err != nil {
		t.Fatalf("Process: %v", err)
	}
	if _, ok := result.CallGraph["fmt.Println"]; ok {
		t.Error("fmt.Println should be skipped as standard library")
	}
	if _, ok := result.CallGraph["filepath.Base"]; ok {
		t.Error("filepath.Base should be skipped as standard library")
	}
	calls, ok := result.CallGraph["helper"]
	if !ok || len(calls) == 0 {
		t.Fatal("local call helper should be recorded")
	}
	if calls[0].ParentFunc != "Run" {
		t.Errorf("helper ParentFunc = %q, want Run", calls[0].ParentFunc)
	}
}

func TestProcessor_ExcludeGenerated(t *testing.T) {
	src := `// Code generated by something. DO NOT EDIT.

package gen

type X struct{}
`
	proc := Processor{ExcludeGenerated: true}
	ctx := context.Background()
	result, err := proc.Process(ctx, "gen/gen.go", []byte(src))
	if err != nil {
		t.Fatalf("Process: %v", err)
	}
	if result.Package != "gen" {
		t.Errorf("Package = %q, want gen", result.Package)
	}
	if len(result.Structs) != 0 {
		t.Errorf("len(Structs) = %d, want 0 (generated should be skipped)", len(result.Structs))
	}
}
