package goparser

import (
	"context"
	"testing"
)

func TestProcessor_Process(t *testing.T) {
	src := `
package pkg

type Foo struct {
	Name string
}

func (f *Foo) Bar() int { return 0 }

type Reader interface {
	Read(p []byte) (n int, err error)
}

func NewFoo() *Foo { return nil }
`
	proc := Processor{}
	ctx := context.Background()
	result, err := proc.Process(ctx, "pkg/foo.go", []byte(src))
	if err != nil {
		t.Fatalf("Process: %v", err)
	}
	if result.Package != "pkg" {
		t.Errorf("Package = %q, want pkg", result.Package)
	}
	if len(result.Structs) != 1 {
		t.Fatalf("len(Structs) = %d, want 1", len(result.Structs))
	}
	if result.Structs[0].Name != "Foo" {
		t.Errorf("Struct name = %q, want Foo", result.Structs[0].Name)
	}
	if len(result.Structs[0].Methods) != 1 {
		t.Errorf("len(Methods) = %d, want 1", len(result.Structs[0].Methods))
	}
	if result.Structs[0].Methods[0].Name != "Bar" {
		t.Errorf("Method name = %q, want Bar", result.Structs[0].Methods[0].Name)
	}
	if len(result.Interfaces) != 1 {
		t.Fatalf("len(Interfaces) = %d, want 1", len(result.Interfaces))
	}
	if result.Interfaces[0].Name != "Reader" {
		t.Errorf("Interface name = %q, want Reader", result.Interfaces[0].Name)
	}
	if len(result.Functions) != 1 {
		t.Fatalf("len(Functions) = %d, want 1", len(result.Functions))
	}
	if result.Functions[0].Name != "NewFoo" {
		t.Errorf("Function name = %q, want NewFoo", result.Functions[0].Name)
	}
}

func TestProcessor_ExcludeGenerated(t *testing.T) {
	src := `// Code generated by something. DO NOT EDIT.

package gen

type X struct{}
`
	proc := Processor{ExcludeGenerated: true}
	ctx := context.Background()
	result, err := proc.Process(ctx, "gen/gen.go", []byte(src))
	if err != nil {
		t.Fatalf("Process: %v", err)
	}
	if result.Package != "gen" {
		t.Errorf("Package = %q, want gen", result.Package)
	}
	if len(result.Structs) != 0 {
		t.Errorf("len(Structs) = %d, want 0 (generated should be skipped)", len(result.Structs))
	}
}
